Repository KTB-Sixmen/gitfolio_back_spring, pull requests merged in 2024-12, with the labels that each got.

#88 🎨 에러 코드 추가
  gitfolio-common/src/main/java/com/be/gitfolio/common/exception/ErrorCode.java
Labels: ✨ Feature

#90 🐛 이력서 관련 버그 수정
  gitfolio-auth/src/main/resources/application.yml
  gitfolio-common/src/main/java/com/be/gitfolio/common/config/WebClientConfig.java
  gitfolio-common/src/main/java/com/be/gitfolio/common/type/PaidPlan.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/controller/MemberController.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/controller/port/MemberService.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/domain/Member.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/domain/MemberAdditionalInfo.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/domain/request/MemberAdditionalInfoRequest.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/domain/request/MemberRequest.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/service/MemberServiceImpl.java
  gitfolio-member/src/main/resources/application.yml
  gitfolio-member/src/test/java/com/be/gitfolio/member/domain/MemberAdditionalInfoTest.java
  gitfolio-member/src/test/java/com/be/gitfolio/member/domain/MemberTest.java
  gitfolio-member/src/test/java/com/be/gitfolio/member/service/MemberServiceTest.java
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/controller/NotificationController.java
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/service/NotificationService.java
  gitfolio-notification/src/main/resources/application.yml
  gitfolio-payment/src/main/resources/application.yml
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/controller/ResumeController.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/domain/Comment.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/ResumeRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/CommentService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/ResumeService.java
  gitfolio-resume/src/main/resources/application.yml
Labels: 🐞 BugFix

#92 🎨 이력서 상세조회 api 분리 및 결제모듈 로직 수정
  gitfolio-common/src/main/java/com/be/gitfolio/common/exception/ErrorCode.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/controller/PaymentController.java
  gitfolio-payment/src/main/resources/application.yml
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/controller/ResumeController.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/domain/Resume.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeRequestDTO.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeResponseDTO.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/ResumeService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/type/Template.java
Labels: ✨ Feature, 🔨 Refactor

#100 🎨 Resume 모듈 Repository DIP 적용
  gitfolio-common/src/main/java/com/be/gitfolio/common/exception/ErrorCode.java
  gitfolio-notification/src/test/java/com/be/gitfolio/notification/service/NotificationServiceTest.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/controller/PaymentController.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/service/PaymentService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/controller/ResumeController.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/domain/Comment.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeRequestDTO.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeResponseDTO.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/ResumeRepositoryCustom.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/comment/CommentJpaRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/comment/CommentRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/like/LikeJpaRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/like/LikeRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/resume/ResumeMongoRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/repository/resume/ResumeRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/CommentService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/LikeService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/ResumeService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/CommentRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/LikeRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/ResumeRepository.java
Labels: 🐞 BugFix, 🔨 Refactor

#106 🌏 Deploy : prod/dev 용 젠킨스파일
  .github/workflows/backcicd.yaml
  .gitignore
  Jenkinsfile
  dockerfile
  gitfolio-auth/dockerfile
  gitfolio-chat/dockerfile
  gitfolio-member/dockerfile
  gitfolio-notification/dockerfile
  gitfolio-payment/dockerfile
  gitfolio-resume/dockerfile
Labels: 🌏 Deploy

#107 🐞 BugFix : 도커파일 gradle 미반영 수정
  dockerfile
Labels: 🐞 BugFix

#109 Update README.md
  README.md
Labels: 📃 Docs

#108 🎨 spring batch 성능 최적화
  .gitignore
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/controller/ReissueController.java
  gitfolio-common/src/main/java/com/be/gitfolio/common/event/KafkaEvent.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/config/MemberBatchConfig.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/domain/Member.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/event/MemberEventPublisher.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/service/MemberServiceImpl.java
  gitfolio-member/src/main/resources/application.yml
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/repository/NotificationJpaRepository.java
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/repository/NotificationRepositoryImpl.java
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/service/NotificationService.java
  gitfolio-notification/src/main/java/com/be/gitfolio/notification/service/port/NotificationRepository.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/config/PaymentBatchConfig.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/infrastructure/PaymentRepository.java
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/service/PaymentService.java
  gitfolio-payment/src/main/resources/application.yml
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/controller/ResumeController.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/comment/CommentJpaRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/comment/CommentRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/like/LikeJpaRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/like/LikeRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/resume/ResumeMongoRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/infrastructure/resume/ResumeRepositoryImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/ResumeService.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/CommentRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/LikeRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/service/port/ResumeRepository.java
  gitfolio-resume/src/main/resources/application.yml
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/mock/FakeResumeRepository.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/service/ResumeServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#113 💡 로그 추가
  gitfolio-payment/src/main/java/com/be/gitfolio/payment/infrastructure/client/KakaoClientImpl.java
Labels: 🌏 Deploy

#114 🎨 회원 탈퇴 버그 수정 및 이력서 요소 수정
  gitfolio-auth/build.gradle
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/controller/ReissueController.java
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/service/CustomOAuth2UserService.java
  gitfolio-auth/src/main/resources/application.yml
  gitfolio-common/src/main/java/com/be/gitfolio/common/config/WebConfig.java
  gitfolio-common/src/main/java/com/be/gitfolio/common/event/KafkaEvent.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/controller/MemberController.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/event/MemberEventPublisher.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/service/MemberServiceImpl.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/domain/Resume.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeRequestDTO.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/mock/FakeCommentRepository.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/mock/FakeLikeRepository.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/service/ResumeServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Test

#116 🐛 cors관련 설정 제거
  gitfolio-common/src/main/java/com/be/gitfolio/common/config/WebConfig.java
Labels: 🌏 Deploy, 🐞 BugFix

#118 🎨 SecurityConfig 수정 및 테스트 코드 수정
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/config/SecurityConfig.java
  gitfolio-member/src/test/java/com/be/gitfolio/member/service/MemberServiceTest.java
  gitfolio-notification/src/test/java/com/be/gitfolio/notification/mock/FakeNotificationRepository.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/domain/ResumeTest.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/mock/FakeAiClient.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/service/CommentServiceTest.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/service/LikeServiceTest.java
  gitfolio-resume/src/test/java/com/be/gitfolio/resume/service/ResumeServiceTest.java
Labels: 🌏 Deploy, 🔨 Refactor

#120 🎨 AI 수정용 dto에 Template 필드 추가
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeRequestDTO.java
Labels: 🐞 BugFix

#123 🚑 Redis Sentinel 설정 추가
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/config/AuthRedisConfig.java
  gitfolio-common/src/main/java/com/be/gitfolio/common/config/RedisConfig.java
  gitfolio-member/src/main/java/com/be/gitfolio/member/config/MemberRedisConfig.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/config/ResumeRedisConfig.java
Labels: 🌏 Deploy

#125 🚑 레디스 관련 버그 수정
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/config/AuthRedisConfig.java
  gitfolio-auth/src/main/java/com/be/gitfolio/auth/infrastructure/RedisTokenRepository.java
  gitfolio-resume/src/main/java/com/be/gitfolio/resume/config/ResumeRedisConfig.java
Labels: 🌏 Deploy, 🐞 BugFix
